// Code generated by go-bindata.
// sources:
// Default.fs.glsl
// Default.vs.glsl
// generate.go
// DO NOT EDIT!

package assets

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _defaultFsGlsl = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x52\x2e\x4b\x2d\x2a\xce\xcc\xcf\x53\x30\x31\x35\xe0\xe5\xe2\xe5\x2a\xcb\xcf\x4c\x51\xc8\x4d\xcc\xcc\xd3\xd0\x54\xa8\x06\x09\xd4\xf2\x72\x01\x02\x00\x00\xff\xff\x2d\x22\xe9\xf7\x24\x00\x00\x00")

func defaultFsGlslBytes() ([]byte, error) {
	return bindataRead(
		_defaultFsGlsl,
		"Default.fs.glsl",
	)
}

func defaultFsGlsl() (*asset, error) {
	bytes, err := defaultFsGlslBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "Default.fs.glsl", size: 36, mode: os.FileMode(438), modTime: time.Unix(1518566235, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _defaultVsGlsl = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x52\x2e\x4b\x2d\x2a\xce\xcc\xcf\x53\x30\x31\x35\xe0\xe5\xe2\xe5\x2a\xcb\xcf\x4c\x51\xc8\x4d\xcc\xcc\xd3\xd0\x54\xa8\x06\x09\xd4\xf2\x72\x01\x02\x00\x00\xff\xff\x2d\x22\xe9\xf7\x24\x00\x00\x00")

func defaultVsGlslBytes() ([]byte, error) {
	return bindataRead(
		_defaultVsGlsl,
		"Default.vs.glsl",
	)
}

func defaultVsGlsl() (*asset, error) {
	bytes, err := defaultVsGlslBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "Default.vs.glsl", size: 36, mode: os.FileMode(438), modTime: time.Unix(1518566235, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _generateGo = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x2c\xca\xb1\x0d\xc4\x30\x08\x05\xd0\x9e\x29\x58\xc0\xd0\xdf\x36\xff\x12\xf4\x15\x59\x32\x56\x60\x7f\xa5\x71\xf7\x8a\xb7\x71\x4d\x30\x14\x55\xd1\x25\x22\xee\xcc\x1f\x63\xc5\x8b\x0e\x65\x8e\xff\xb3\x6e\x34\x74\xec\xc9\xd3\x74\xe4\x91\x31\xd5\xdc\xcc\xe4\x0b\x00\x00\xff\xff\xe5\xe0\x7c\x21\x49\x00\x00\x00")

func generateGoBytes() ([]byte, error) {
	return bindataRead(
		_generateGo,
		"generate.go",
	)
}

func generateGo() (*asset, error) {
	bytes, err := generateGoBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "generate.go", size: 73, mode: os.FileMode(438), modTime: time.Unix(1518566313, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"Default.fs.glsl": defaultFsGlsl,
	"Default.vs.glsl": defaultVsGlsl,
	"generate.go": generateGo,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"Default.fs.glsl": &bintree{defaultFsGlsl, map[string]*bintree{}},
	"Default.vs.glsl": &bintree{defaultVsGlsl, map[string]*bintree{}},
	"generate.go": &bintree{generateGo, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

